name: Documentation Quality

on:
  push:
    branches: [ main ]
    paths:
      - '**.org'
      - '**.md'
      - '.vale.ini'
      - '.vale/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**.org'
      - '**.md'
      - '.vale.ini'
      - '.vale/**'

jobs:
  vale:
    name: Vale Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          files: '*.org'
          reporter: github-check
          level: error
          fail_on_error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
