name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Guile
        run: |
          sudo apt-get update
          sudo apt-get install -y guile-3.0 guile-3.0-dev

      - name: Build
        run: make

      - name: Run Tests
        run: make test

      - name: Check Build Artifacts
        run: |
          test -f roulette.go
          test -f roulette/core.go
          test -f roulette/inference.go
